repository_type: pipeline

nf_core_version: 3.5.1

lint:
  files_unchanged:
    - assets/nf-core-rarediseaserefs_logo_light.png

template:
  org: nf-core
  name: rarediseaserefs
  description: A pipeline to download reference files needed to run nf-core/raredisease.
  author: Ramprasad Neethiraj
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
